version: "2.2"
services:
   frontend:
      build: ./frontend
      ports:
         - 3000:3000
      environment:
         WATCHPACK_POLLING: true
      volumes:
         - ./frontend:/app
      depends_on:
         - backend
   backend:
      build: ./backend
      ports:
         - 3001:3001
      volumes:
         - ./backend:/app
      depends_on:
         - db
   db:
      image: mongo:4.0.28-xenial
      ports:
         - 27017:27017
      volumes:
         - breathing-lines:/data/db

volumes:
   breathing-lines:
