name: CI

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   docker:
      timeout-minutes: 10
      runs-on: ubuntu-latest

      env:
         MONGOATLAS_URI_TEST: ${{ secrets.MONGOATLAS_URI_TEST }}
         JWT_SECRET: ${{ secrets.JWT_SECRET }}

      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Start containers
           run: docker-compose -f "docker-compose.yml" up -d --build

         - name: Install node
           uses: actions/setup-node@v3
           with:
              node-version: "20"

         - name: Install root dependencies
           run: npm install

         - name: Install backend dependencies
           working-directory: ./backend
           run: npm install

         - name: Install frontend dependencies
           working-directory: ./frontend
           run: npm install

         - name: Run Unit Tests
           run: npm run test:unit

         - name: Run React Component Tests
           working-directory: ./frontend
           run: npm run test

         - name: Run DB Integration Tests
           working-directory: ./backend
           run: npm run test:db-integration

         - name: Run ESLint tests
           run: npm run lint

         - name: Stop & remove containers
           if: always()
           run: docker-compose -f "docker-compose.yml" down
